import { colors, SEVERITY } from "../theme";

/*
 * InsightBanner — Claude's #1 observation, surfaced at the top of the
 * dashboard. The thin colored left border + tinted background read at a
 * glance; the headline is bold, the detail explains in plain language.
 *
 * Three visual states:
 *   1. loading + no insight yet  → "Reading your <entities>…"
 *   2. insight present           → severity-colored card (info/warning/alert)
 *   3. no insight, not loading   → render nothing
 *
 * Props:
 *   insight        — { headline, detail, severity } from /api/insights
 *   loading        — boolean, controls the loading state
 *   loadingLabel   — what to show while loading (e.g., "your campaigns")
 */
export const InsightBanner = ({ insight, loading, loadingLabel = "your data" }) => {
  if (!insight && !loading) return null;
  if (loading && !insight) {
    return (
      <div style={{
        background: colors.panel,
        border: `1px solid ${colors.panelBorder}`,
        borderLeft: `4px solid ${colors.textDim}`,
        borderRadius: 8,
        padding: "0.85rem 1rem",
        marginBottom: "1.25rem",
        fontSize: "0.8rem",
        color: colors.textDim,
        fontStyle: "italic"
      }}>
        Reading {loadingLabel}…
      </div>
    );
  }

  const sev = SEVERITY[insight.severity] || SEVERITY.info;
  return (
    <div style={{
      background: sev.tint,
      border: `1px solid ${colors.panelBorder}`,
      borderLeft: `4px solid ${sev.color}`,
      borderRadius: 8,
      padding: "0.85rem 1rem",
      marginBottom: "1.25rem"
    }}>
      <div style={{ display: "flex", alignItems: "center", gap: "0.6rem", marginBottom: "0.4rem" }}>
        <span style={{
          color: sev.color,
          fontSize: "0.65rem",
          fontWeight: 700,
          letterSpacing: "0.08em"
        }}>
          {sev.label}
        </span>
        <span style={{ color: colors.textDim, fontSize: "0.65rem" }}>· generated by Claude</span>
      </div>
      <div style={{
        color: colors.text,
        fontSize: "0.95rem",
        fontWeight: 600,
        lineHeight: 1.3,
        marginBottom: "0.3rem"
      }}>
        {insight.headline}
      </div>
      <div style={{ color: colors.textDim, fontSize: "0.8rem", lineHeight: 1.4 }}>
        {insight.detail}
      </div>
    </div>
  );
};
